name: Build Book

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  mdbook-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mdBook
        run: cargo install mdbook --locked

      - name: Build
        run: mdbook build
